### ISSUE TITLE
Persists logs to Kafka

### ISSUE THREAD

**Issue by satybald** [yahoojapan/presto-audit#7]
What does a community think about a feature to persists logs to another message broker Kafka? Does anyone find the feature useful for the project?

**Comment by oneonestar** [comment]
You may write your own logic to persists logs by implementing an [event-listener](https://prestodb.io/docs/current/develop/event-listener.html) plugin.
If you want to send logs to Kafka, you can find an example here: https://github.com/Shopify/presto-logging-plugin

**Comment by satybald** [comment]
awesome! Didn't know that there's already a project for that ;) thanks a lot @oneonestar!
